desi/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'desi.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'all.views.index', name='home'),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^admin/doc', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^qualifications/', include('qualifications.urls', namespace="qualifications")),
    url(r'^clients/', include('clients.urls', namespace="clients")),
    url(r'^about/', 'all.views.about', name='about'),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^careers/', include('careers.urls', namespace='careers')),
    url(r'^services/', include('services.urls', namespace='services')),
)

projects/urls.py
from django.conf.urls import patterns, url

from projects import views

urlpatterns = patterns('', 
    #ex: /projects/
    url(r'^$', views.index, name='index'),
    #ex: /projects/5/
    url(r'^(?P<proj_name_short>\w+)/$', views.detail, name='detail'),
)

qualifications/urls.py
from django.conf.urls import patterns, url

from qualifications import views

urlpatterns = patterns('', 
    #ex: /projects/
    url(r'^$', views.index, name='index'),
)

all/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models

from clients.models import Client


class ServiceCategory(models.Model):
    name = models.CharField(max_length=200, unique=True)
    subheading = models.CharField(max_length=200, blank=True)
    description = models.TextField()

    def __str__(self):
        return self.name

class ServiceImage(models.Model):
    image = models.ImageField(upload_to='service_images/')
    category = models.ForeignKey(ServiceCategory)

    def __str__(self):
        return "image in " + str(self.category)

class ProjectService(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(ServiceCategory)

    def __str__(self):
        return self.name

class ProjectCategory(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name

class ProjectOwner(models.Model):
    name = models.CharField(max_length=200)
    address = models.TextField(blank=True)

    def __str__(self):
        return self.name

class ProjectLocation(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name

class Project(models.Model):
    category = models.ForeignKey(ProjectCategory)
    desi_id = models.CharField(max_length=200, unique=True)
    name_long = models.CharField(max_length=200)
    name_short = models.CharField("name to use as url", max_length=200, unique=True)
    description = models.TextField()
    services = models.ManyToManyField(ProjectService)
    project_owner = models.ForeignKey(ProjectOwner, blank=True, null=True)
    project_client = models.ForeignKey(Client, blank=True)
    owner_is_client = models.BooleanField()
    project_location = models.ForeignKey(ProjectLocation)
    use_in_carousel = models.BooleanField()

    def __str__(self):
        return self.name_long

class ProjectImage(models.Model):
    image = models.ImageField(upload_to='project_images/')
    side_image = models.BooleanField()
    project = models.ForeignKey(Project)
    is_main_image = models.BooleanField()

qualifications/models.py
from django.db import models

class QualCategory(models.Model):
    name = models.CharField(max_length=200)
    name_short = models.CharField("name to use in link (must have no spaces)", max_length=20, unique=True)

    def __str__(self):
        return self.name

class Qualification(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='qualifications/', blank=True)
    category = models.ForeignKey(QualCategory)

    def __str__(self):
        return self.name

all/views.py
from django.shortcuts import render

from projects.models import Project, ProjectImage, ProjectService, ServiceCategory
from news.models import Article

from markdown import markdown
from datetime import date

from utils.strings import strip_md

def index(request):
    carousel_projects = Project.objects.filter(use_in_carousel=True)
    main_images = ProjectImage.objects.filter(is_main_image=True)
    for project in carousel_projects:
        project.main_image = [image for image in main_images if image.project_id == project.id]

    carousel_range = range(len(carousel_projects))

    start_date = date(2014, 7, 1)
    now = date.today()
    news = Article.objects.order_by('date').reverse().filter(date__range=(start_date,now))[:3]
    for article in news:
    	article.text = strip_md(article.text)

    return render(request, 'all/index.html', {'carousel_projects': carousel_projects, 'carousel_range': carousel_range, 'news': news})

def services(request):
	categories = ServiceCategory.objects.all()
	services = ProjectService.objects.all()
	for category in categories:
		category.services = [service for service in services if service.category_id == category.id]

	return render(request, 'all/services.html', {})



def contact(request):
	return render(request, 'all/contact.html', {})

def about(request):
	return render(request, 'all/about.html', {})

projects/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse
from django.template import RequestContext, loader
from projects.models import Project, ProjectCategory, ProjectImage
from django.views import generic

from utils.strings import strip_md

def index(request):
    project_categories = ProjectCategory.objects.all()
    projects = Project.objects.all()
    images = ProjectImage.objects.all()
    for project in projects:
        project.main_image = [image for image in images if image.project_id == project.id and image.is_main_image]
        project.plain_desc = strip_md(project.description)
    for category in project_categories:
        category.projects = [project for project in projects if project.category_id == category.id]
    return render(request, 'projects/index.html', { 'project_categories': project_categories })

def detail(request, proj_name_short):
    project = get_object_or_404(Project, name_short=proj_name_short)
    images = ProjectImage.objects.all()
    side_images = []
    normal_images = []
    for image in images:
        if image.project_id == project.id:
            if image.side_image:
                side_images.append(image)
            elif image.is_main_image:
                project.main_image = image
            else:
                normal_images.append(image)    

    return render(request, 'projects/detail.html', {'project': project, 'side_images': side_images, 'normal_images': normal_images,})


def categoryPrettyPrint(category):
    return category.name + ': ' + ', '.join([project.name_long for project in category.projects])

qualifications/views.py
from django.shortcuts import render

from qualifications.models import QualCategory, Qualification

def index(request):
    qual_categories = QualCategory.objects.all()
    quals = Qualification.objects.order_by('name')
    for category in qual_categories:
        category.quals = [qual for qual in quals if qual.category_id == category.id]

    return render(request, 'qualifications/index.html', { 'qualification_categories': qual_categories, })

templates/all/base.html
{% load staticfiles %}

<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {% block stylesheets %}
            <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" />
            <link rel="stylesheet" href="{% static "css/base.css" %}" type="text/css" media="screen" />
        {% endblock %}
        {% block javascript %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
            <script src="{% static "js/bootstrap.min.js" %}"></script>
            <script src="{% static "js/jquery.dotdotdot.min.js" %}"></script>
        {% endblock %}
        <title>{% block title %}Page{% endblock %} | Distinct Engineering Solutions, Inc.</title>
        {% block extra_head %}{% endblock %}      
    </head>
    <body>
        {% include "all/navigation.html" %}
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        {% include "all/footer.html" %}
        {% block bodyjavascript %}
        {% endblock %}
    </body>
</html>

templates/all/index.html
{% extends "all/base.html" %}
{% load staticfiles %}

{% block title %}Home{% endblock %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static "css/home.css" %}" type="text/css" media="screen">
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-8 text-justify col-xs-12">
			<p>Distinct Engineering Solutions, Inc is an engineering consulting firm with a mission to provide solutions that are tailored to meet clients’ needs, project specifications and budget, bringing synergy to design and construction projects. Our vision is to establish a sound relationship with our clients through providing responsive and cost effective solutions for projects we are involved in and the communities we serve.</p>
			{% include "all/project_carousel.html" with carousel_projects=carousel_projects carousel_range=carousel_range %}
		</div>
		<div class="col-md-4 col-xs-12">
			{% include "all/news.html" with news=news %}
		</div>
	</div>
{% endblock %}

{% block bodyjavascript %}
    <script src="{% static "js/home.js" %}"></script>
{% endblock %}

templates/all/navigation.html
{% load staticfiles %}

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url "home" %}">
                <img src="{% static "img/logocolor.png" %}" class="logo" />
                <span class="hidden-sm"><strong>Distinct</strong> Engineering</span> <span class="hidden-sm hidden-md">Solutions<span class="hidden-xs">, Inc.</span></span>
            </a>
        </div>  

        <div class="collapse navbar-collapse">
            <form class="navbar-right visible-lg" action="{% url "admin:index" %}">
                <button type="submit" class="btn btn-default navbar-btn">Sign In</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% include "all/navlinks.html" %}
            </ul>
        </div>
    </div>
</nav>

templates/projects/detail.html
{% extends "projects/project_base.html" %}
{% load staticfiles %}
{% load markdown_deux_tags %}

{% block title %}{{ project.name_long }}{% endblock %}

{% block content %}
<div class="row page-header">
    <div class="col-md-12">
        <h2>{{project.name_long}} <small>{{ project.project_location }}</small></h2>
    </div>
</div>
<div class="row">
    <div class="col-md-9 col-md-push-3 text-justify">
        <p><strong>Project Overview:</strong></p>
        <p>{{ project.description|markdown }}</p>
        {% if project.main_image %}
            <img src="{{ project.main_image.image.url }}" class="img-responsive normal_image main_image" />
        {% endif %}
        {% for image in normal_images %}
            <img src="{{ image.image.url }}" class="img-responsive normal_image" />
        {% endfor %}
    </div>
    <div class="col-md-3 col-md-pull-9">
        <p><strong>Services:</strong></p>
        <ul class="list-unstyled">
            {% for service in project.services.all %}
                <li>{{ service.name }}</li>
            {% endfor %}
        </ul>
        {% for image in side_images %}
            <img src="{{ image.image.url }}" class="img-responsive side_image" />
        {% endfor %}
        {% if not project.owner_is_client %}
            {% with owner=project.project_owner %}
                <p><strong>Owner:</strong></p>
                <address>
                    <p>{{ owner.name }}<br />{{ owner.address|linebreaksbr }}</p>
                </address>
            {% endwith %}
        {% endif %}
        {% with client=project.project_client %}
            <p><strong>Client {% if project.owner_is_client %} and Owner{% endif %}:</strong></p>
            <address>
                <p>{{ client.name }}<br />{{ client.address|linebreaksbr }}</p>
            </address>
        {% endwith %}
    </div>
</div>

{% endblock %}

templates/projects/index.html
{% extends "projects/project_base.html" %}
{% load staticfiles %}

{% block title %}Projects{% endblock %}


{% block content %}
<div class="row">
    <nav class="col-lg-3 hidden-sm hidden-xs hidden-md sidebar-top">
        {% include "projects/project_sidebar.html" with project_categories=project_categories %}
    </nav>
    <div class="col-lg-9 col-md-12">
    {% if project_categories %}
        {% for category in project_categories %}
            <section id="Cat{{ category.id }}" class="group">
                <h3 class="page-header">{{ category.name }}</h3>
                {% for project in category.projects %}
                <div class="row subgroup preview" id="Proj{{ project.id }}">
                    {% include "projects/project_preview.html" with project=project %}
                </div>
                {% endfor %}
            </section>
        {% endfor %}
    {% else %}
        <p>No Project Categories Exist</p>
    {% endif %}
    </div>
</div>
{% endblock %}

{% block bodyjavascript %}
    <script src="{% static "js/project_index.js" %}"></script>
{% endblock %}

templates/projects/project_base.html
{% extends "all/base.html" %}
{% load staticfiles %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static "css/sidebar.css" %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static "css/project.css" %}" type="text/css" media="screen">
{% endblock %}

templates/projects/project_preview.html
<div class="col-md-4 col-sm-4 col-xs-6">
	<a href="{% url 'projects:detail' project.name_short %}" class="thumbnail">
    	<img src="{% if project.main_image %}{{ project.main_image.0.image.url }}{% endif %}" class="img-responsive" />
	</a>
</div>
<div class="col-md-8 col-sm-8 col-xs-6 wrapper">
	<a href="{% url 'projects:detail' project.name_short %}" class="box_link">
    	<h4>{{ project.name_long }}</h4>
    	<p><strong>Location:</strong> {{ project.project_location }}</p>
    	{% if not project.owner_is_client %}
    	<p><strong>Owner:</strong> {{ project.project_owner }}
    	{% endif %}
    	<strong>Client {% if project.owner_is_client %} and Owner{% endif %}:</strong>  {{ project.project_client }}</p>
    	<p class="text-justify">{{ project.plain_desc }}<a class="readmore" href="{% url 'projects:detail' project.name_short %}">Read more</a></p>
    </a>
</div>

templates/projects/project_sidebar.html
{% if project_categories %}
<ul class="nav nav-stacked fixed" id="sidebar">
    {% for category in project_categories %}
    <li>
        <a href="#Cat{{ category.id }}">{{ category.name }}</a>
        <ul class="nav nav-stacked" >
            {% for project in category.projects %}
            <li><a href="#Proj{{ project.id }}">{{ project.name_long }}</a></li>
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>
{% endif %}

templates/qualifications/index.html
{% extends "all/base.html" %}
{% load staticfiles %}

{% block title %}Qualifications{% endblock%}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static "css/qualifications.css" %}" type="text/css" media="screen">
{% endblock %}

{% block content %}
	<h3 class="page-header">Qualifications</h3>
	<div class="panel-group" id="accordion">
		{% for category in qualification_categories %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">
						<a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ category.name_short }}">
							{{ category.name }}
						</a>
					</h4>
				</div>
				<div id="collapse{{ category.name_short }}" class="panel-collapse collapse in">
					<div class="panel-body">
						<ul class="qualification-list">
							{% for qual in category.quals %}
								<li>{% if qual.image %}<a href="{{ qual.image.url }}">{% endif %}{{ qual.name }}{% if qual.image %}</a>{% endif %}</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock %}

{% block bodyjavascript %}
	<script src="{% static "js/qualifications.js" %}"></script>
{% endblock %}